#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Eric Kow
# License: CeCILL (French BSD3-like)

"""
IRIT STAC experimental harness
"""

import argparse

from stac.harness.cmd import SUBCOMMANDS


def main():
    "harness main (subcommands are likely more interesting)"

    arg_parser = \
        argparse.ArgumentParser(description='IRIT STAC harness')
    subparsers = arg_parser.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        subparser = subparsers.add_parser(module.NAME,
                                          help=module.__doc__)
        module.config_argparser(subparser)

    arg_parser.add_argument('--verbose', '-v',
                            action='count',
                            default=0)
    args = arg_parser.parse_args()
    args.func(args)

main()
