svn delete data/pilot/pilot01/glozz_annotations/hjoseph
svn delete data/pilot/pilot01/glozz_annotations/jhall
svn delete data/pilot/pilot01/glozz_annotations/lpetersen
svn delete data/pilot/pilot01/glozz_annotations/mhunt
svn delete data/pilot/pilot01/glozz_annotations/ResultUnit
svn delete data/pilot/pilot01/Gold
svn delete data/pilot/pilot02/glozz_annotations/hjoseph
svn delete data/pilot/pilot02/glozz_annotations/jhall
svn delete data/pilot/pilot02/glozz_annotations/lpetersen
svn delete data/pilot/pilot02/glozz_annotations/mhunt
svn delete data/pilot/pilot02/Gold
svn delete data/pilot/pilot03/glozz_annotations/hjoseph
svn delete data/pilot/pilot03/glozz_annotations/jhall
svn delete data/pilot/pilot03/glozz_annotations/lpetersen
svn delete data/pilot/pilot03/glozz_annotations/mhunt
svn delete data/pilot/pilot03/Gold
svn delete data/pilot/pilot04/glozz_annotations/hjoseph
svn delete data/pilot/pilot04/glozz_annotations/jhall
svn delete data/pilot/pilot04/glozz_annotations/lpetersen
svn delete data/pilot/pilot04/glozz_annotations/mhunt
svn delete data/pilot/pilot04/Gold
svn delete data/pilot/pilot14/glozz_annotations/hjoseph
svn delete data/pilot/pilot14/glozz_annotations/jhall
svn delete data/pilot/pilot14/glozz_annotations/lpetersen
svn delete data/pilot/pilot14/glozz_annotations/mhunt
svn delete data/pilot/pilot14/Gold
svn delete data/pilot/pilot20/glozz_annotations/hjoseph
svn delete data/pilot/pilot20/glozz_annotations/jhall
svn delete data/pilot/pilot20/glozz_annotations/lpetersen
svn delete data/pilot/pilot20/glozz_annotations/mhunt
svn delete data/pilot/pilot20/Gold
svn delete data/pilot/pilot21/glozz_annotations/hjoseph
svn delete data/pilot/pilot21/glozz_annotations/jhall
svn delete data/pilot/pilot21/glozz_annotations/lpetersen
svn delete data/pilot/pilot21/glozz_annotations/mhunt
svn delete data/pilot/pilot21/pred_arg_annotations/joseph
