#!/bin/bash

# svn delete a file if it's an empty directory

if [ $# -ne 1 ]; then
     echo >&2 "Usage: $0 DIR"
     exit 1
fi

d=$1

if [ -d "$d" ]; then
    num_files=$(ls "$d" | wc -l | awk '{print $0}')
    if [ $num_files -eq 0 ]; then
        echo svn delete $d
    fi
fi
