#!/bin/bash

# Move annotations from a subset of annotators whose data
# we're no longer using to a separate directory.
#
# Note that this only works if you don't have spaces in filenames

mkdir -p data/pilot-discards
for anno in mhunt jhall; do
    for f in $(find data/pilot -name $anno -type d); do
        f2=$(echo $f | sed -e 's!data/pilot!data/pilot-discards!')
        mkdir -p $(dirname $f2)
        git mv $f $f2
    done
done
