#!/bin/bash

# Build models from extracted features.
# You should run gather-features first

pushd $(dirname $0) > /dev/null
SCRIPT_DIR=$PWD
popd > /dev/null
cd $SCRIPT_DIR/../..

SNAPSHOT=$PWD/data/SNAPSHOTS/latest
ATTELO_LEARNER=bayes
ATTELO_CONFIG="$SCRIPT_DIR/stac-features.config"
DATASETS="socl-season1 pilot"

if [ ! -d "$SNAPSHOT" ]; then
    echo >&2 "No data snapshot detected; please run $SCRIPT_DIR/gather-features"
    exit 1
fi

T=$(mktemp -d -t stac.XXXX)
pushd "$T" > /dev/null
for dset in "all $DATASETS"; do
    echo >&2 "[build model] learning models for dataset $dset"
    attelo learn -C "$ATTELO_CONFIG" -l "$ATTELO_LEARNER"\
        "$SNAPSHOT/$dset.edu-pairs.csv"\
        "$SNAPSHOT/$dset.relations.csv"
    for m in "$T"/*.model; do
        mv $m "$SNAPSHOT"/$(basename $m)-$dset.model
    done
done
popd > /dev/null
