#!/bin/bash

# Build models from extracted features.
# You should run gather-features first

pushd $(dirname $0) > /dev/null
SCRIPT_DIR=$PWD
popd > /dev/null
cd $SCRIPT_DIR/../..

die () {
    errcode=$?
    echo "ARGH! Something went wrong building the model"
    exit $errcode
}
trap die ERR



SNAPSHOT=$PWD/data/SNAPSHOTS/latest
ATTELO_LEARNERS="bayes maxent"
ATTELO_CONFIG="$SCRIPT_DIR/stac-features.config"
DATASETS="socl-season1 pilot"

if [ ! -d "$SNAPSHOT" ]; then
    echo >&2 "No data snapshot detected; please run $SCRIPT_DIR/gather-features"
    exit 1
fi

T=$(mktemp -d -t stac.XXXX)
pushd "$T" > /dev/null
for dset in all $DATASETS; do
    for learner in $ATTELO_LEARNERS; do
        echo >&2 "[build model] learning $learner models for dataset $dset"
        attelo learn -C "$ATTELO_CONFIG" -l "$learner"\
            "$SNAPSHOT/$dset.edu-pairs.csv"\
            "$SNAPSHOT/$dset.relations.csv"
        for m in "$T"/*.model; do
            mv $m "$SNAPSHOT"/"$(basename $m .model)-$dset-$learner".model
        done
    done
done
popd > /dev/null
