#!/bin/bash

pushd $(dirname $0) > /dev/null
SCRIPT_DIR=$PWD
popd > /dev/null
cd $SCRIPT_DIR/../..

TODAY=$(date +%Y-%m-%d)
SNAPSHOT=$PWD/data/SNAPSHOTS/$TODAY
LEX_DIR=data/resources/lexicon
ANNO='bronze|Bronze|silver|SILVER|GOLD'
DATASETS="socl-season1 pilot"

mkdir -p $SNAPSHOT/tmp

die () {
    errcode=$?
    echo "ARGH! Something went wrong; check the log files in $SNAPSHOT/tmp"
    exit $errcode
}
trap die ERR

for dset in $DATASETS; do
    echo >&2 "gathering features for $dset"
    code/queries/rel-info data/$dset $LEX_DIR "$SNAPSHOT/tmp"\
        --experimental\
        --anno $ANNO\
        2> "$SNAPSHOT/tmp/$dset.features.log"
done
mv $SNAPSHOT/tmp/*.csv $SNAPSHOT

# combine the csv files into one megafile
head -n 1 "$SNAPSHOT/pilot.edu-pairs.csv" > "$SNAPSHOT/all.edu-pairs.csv"
head -n 1 "$SNAPSHOT/pilot.relations.csv" > "$SNAPSHOT/all.relations.csv"
for dset in $DATASETS; do
    tail -n +2 "$SNAPSHOT/$dset.edu-pairs.csv"\
        >> "$SNAPSHOT/all.edu-pairs.csv"
    tail -n +2 "$SNAPSHOT/$dset.relations.csv"\
        >> "$SNAPSHOT/all.relations.csv"
done

# symlink this as the latest snapshot we have
pushd data/SNAPSHOTS > /dev/null
rm -f latest
ln -s $TODAY latest
popd > /dev/null
