#!/bin/bash

ZERODIR=$(dirname "$0")
pushd "$ZERODIR" > /dev/null
SCRIPT_DIR=$PWD
popd > /dev/null
cd "$SCRIPT_DIR/../.."

TODAY=$(date +%Y-%m-%d)
SNAPSHOT=$PWD/data/SNAPSHOTS/$TODAY
LEX_DIR=data/resources/lexicon
ANNO='bronze|Bronze|silver|SILVER|GOLD'
DATASETS="socl-season1 pilot"
WINDOW="5" # "-1" for no window

mkdir -p "$SNAPSHOT/tmp"

die () {
    errcode=$?
    echo "ARGH! Something went wrong; check the log files in $SNAPSHOT/tmp"
    exit $errcode
}
trap die ERR

for dset in $DATASETS; do
    echo >&2 "gathering features for $dset"
    code/queries/rel-info "data/$dset" "$LEX_DIR" "$SNAPSHOT/tmp"\
        --experimental\
        --anno "$ANNO"\
        --window "$WINDOW"\
        2> "$SNAPSHOT/tmp/$dset.features.log"
    code/queries/rel-info "data/$dset" "$LEX_DIR" "$SNAPSHOT/tmp"\
        --experimental\
        --single\
        --anno "$ANNO"\
        2>> "$SNAPSHOT/tmp/$dset.features.log"
done
mv "$SNAPSHOT"/tmp/*.csv "$SNAPSHOT"

# combine the csv files into one megafile
for ext in edu-pairs relations just-edus; do
    head -n 1 "$SNAPSHOT/pilot.$ext.csv" > "$SNAPSHOT/all.$ext.csv"
    for dset in $DATASETS; do
        tail -n +2 "$SNAPSHOT/$dset.$ext.csv"\
            >> "$SNAPSHOT/all.$ext.csv"
    done
done

# symlink this as the latest snapshot we have
pushd data/SNAPSHOTS > /dev/null
rm -f latest
ln -s "$TODAY" latest
popd > /dev/null
