#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Author: Eric Kow
# License: BSD3

"""
RST_DT Swiss-Army knife
"""

import argparse

from rst_dt.cmd import SUBCOMMANDS


def main():
    "rst-util main"

    arg_parser = argparse.ArgumentParser(description='RST-DT Swiss Army Knife')
    subparsers = arg_parser.add_subparsers(help='sub-command help')

    for module in SUBCOMMANDS:
        subparser = subparsers.add_parser(module.NAME,
                                          help=module.__doc__)
        module.config_argparser(subparser)

    arg_parser.add_argument('--verbose', '-v',
                            action='count',
                            default=0)
    args = arg_parser.parse_args()
    args.func(args)

main()
