#!/usr/bin/env python

# Author: Eric Kow
# License: BSD3

import copy
import csv
import sys

def segment(t):
    return t

filename_in  = sys.argv[1]
filename_out = sys.argv[2]

csv.register_dialect('stac', delimiter='\t', lineterminator='\n', quoting=csv.QUOTE_NONNUMERIC)

with open(filename_in, 'rb') as infile:
    with open(filename_out, 'wb') as outfile:
        reader = csv.reader(infile,  delimiter='\t')
        writer = csv.writer(outfile, dialect='stac')
        for row in reader:
            row2     = copy.copy(row)
            row2[-3] = segment(row[-3])
            writer.writerow(row2)
